/*
 lazysizes - v5.3.2 */
'use strict';window.Element&&!Element.prototype.closest&&(Element.prototype.closest=function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);var f=this,k;do for(k=a.length;0<=--k&&a.item(k)!==f;);while(0>k&&(f=f.parentElement));return f});
window.Element&&!Element.prototype.matches&&(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||Element.prototype.webkitMatchesSelector||function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);for(var f=a.length;0<=--f&&a.item(f)!==this;);return-1<f});
Object.assign||(Object.assign=function(a,f){if(null===a)throw new TypeError("Cannot convert undefined or null to object");for(var k=Object(a),b=1;b<arguments.length;b++){var h=arguments[b];if(null!==h)for(var e in h)Object.prototype.hasOwnProperty.call(h,e)&&(k[e]=h[e])}return k});
(function(a){a.forEach(function(a){a.hasOwnProperty("remove")||Object.defineProperty(a,"remove",{configurable:!0,enumerable:!0,writable:!0,value:function(){this.parentNode.removeChild(this)}})})})([Element.prototype,CharacterData.prototype,DocumentType.prototype]);
(function(){function a(c){c=c.dataset;var a=[],e="image";e=e.charAt(0).toUpperCase()+e.slice(1);e=["is","hook"+e];for(var d in c)if(c.hasOwnProperty(d)){var b=c[d];0===d.indexOf("cmp")&&(d=d.slice(3),d=d.charAt(0).toLowerCase()+d.substring(1),-1===e.indexOf(d)&&(a[d]=b))}return a}function f(a){function f(d){d.element.removeAttribute("data-cmp-is");var a=d.options;g._properties={};for(var c in e)if(e.hasOwnProperty(c)){var f=e[c];g._properties[c]=a&&null!=a[c]?f&&"function"===typeof f.transform?f.transform(a[c]):
a[c]:e[c]["default"]}d=d.element;g._elements={};g._elements.self=d;d=g._elements.self.querySelectorAll("[data-cmp-hook-image]");for(a=0;a<d.length;a++)c=d[a],f="image",f=f.charAt(0).toUpperCase()+f.slice(1),g._elements[c.dataset["cmpHook"+f]]=c;if(g._elements.noscript){g._elements.container=g._elements.link?g._elements.link:g._elements.self;d=g._elements.noscript.textContent.trim();d=d.replace(/&(amp;)*lt;/g,"\x3c");d=d.replace(/&(amp;)*gt;/g,"\x3e");d=(new DOMParser).parseFromString(d,"text/html");
a=d.querySelector(b.image);a.removeAttribute("src");g._elements.container.insertBefore(a,g._elements.noscript);(d=d.querySelector(b.map))&&g._elements.container.insertBefore(d,g._elements.noscript);g._elements.noscript.parentNode.removeChild(g._elements.noscript);g._elements.container.matches(b.image)?g._elements.image=g._elements.container:g._elements.image=g._elements.container.querySelector(b.image);g._elements.map=g._elements.container.querySelector(b.map);g._elements.areas=g._elements.container.querySelectorAll(b.area);
if(g._properties.lazy){d=g._elements.image.getAttribute("width");a=g._elements.image.getAttribute("height");if(d&&a){c=h.style;c["padding-bottom"]=a/d*100+"%";for(var k in c)c.hasOwnProperty(k)&&(g._elements.image.style[k]=c[k])}g._elements.image.setAttribute("src","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");g._elements.image.classList.add(h.cssClass);g._lazyLoaderShowing=!0}g._elements.map&&g._elements.image.addEventListener("load",K);window.addEventListener("scroll",
g.update);window.addEventListener("resize",m);window.addEventListener("update",g.update);g._elements.image.addEventListener("cmp-image-redraw",g.update);g.update()}}function k(){var a=g._properties.widths&&0<g._properties.widths.length;if(a){var e=g._elements.self;for(var b=e.clientWidth;0===b&&e.parentNode;)e=e.parentNode,b=e.clientWidth;e=b*c;b=g._properties.widths.length;for(var h=0;h<b-1&&g._properties.widths[h]<e;)h++;e="."+g._properties.widths[h].toString()}else e="";e=g._properties.src.replace("{.width}",
e);g._elements.image.getAttribute("src")!==e&&(g._elements.image.setAttribute("src",e),a||window.removeEventListener("scroll",g.update));g._lazyLoaderShowing&&g._elements.image.addEventListener("load",d)}function d(){g._elements.image.classList.remove(h.cssClass);for(var a in h.style)h.style.hasOwnProperty(a)&&(g._elements.image.style[a]="");g._elements.image.removeEventListener("load",d);g._lazyLoaderShowing=!1}function y(){if(g._elements.areas&&0<g._elements.areas.length)for(var d=0;d<g._elements.areas.length;d++){var a=
g._elements.image.width,c=g._elements.image.height;if(a&&c){var e=g._elements.areas[d].dataset.cmpRelcoords;if(e){e=e.split(",");for(var b=Array(e.length),h=0;h<b.length;h++)b[h]=0===h%2?parseInt(e[h]*a):parseInt(e[h]*c);g._elements.areas[d].coords=b}}}}function m(){g.update();y()}function K(){y()}var g=this;g.update=function(){if(g._properties.lazy){if(null===g._elements.container.offsetParent)var d=!1;else{d=window.pageYOffset;var a=d+document.documentElement.clientHeight,c=g._elements.container.getBoundingClientRect().top+
d;d=c+g._elements.container.clientHeight>=d-0&&c<=a+0}d&&k()}else k()};a&&a.element&&f(a)}function k(){for(var c=document.querySelectorAll(b.self),e=0;e<c.length;e++)new f({element:c[e],options:a(c[e])});c=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;e=document.querySelector("body");(new c(function(c){c.forEach(function(d){d=[].slice.call(d.addedNodes);0<d.length&&d.forEach(function(d){d.querySelectorAll&&[].slice.call(d.querySelectorAll(b.self)).forEach(function(d){new f({element:d,
options:a(d)})})})})})).observe(e,{subtree:!0,childList:!0,characterData:!0})}var b={self:'[data-cmp-is\x3d"image"]',image:'[data-cmp-hook-image\x3d"image"]',map:'[data-cmp-hook-image\x3d"map"]',area:'[data-cmp-hook-image\x3d"area"]'},h={cssClass:"cmp-image__image--is-loading",style:{height:0,"padding-bottom":""}},e={widths:{"default":[],transform:function(c){var a=[];c.split(",").forEach(function(c){c=parseFloat(c);isNaN(c)||a.push(c)});return a}},lazy:{"default":!1,transform:function(c){return!(null===
c||"undefined"===typeof c)}},src:{}},c=window.devicePixelRatio||1;"loading"!==document.readyState?k():document.addEventListener("DOMContentLoaded",k)})();
(function(){function a(a){a=a.dataset;var c=[],e="formText";e=e.charAt(0).toUpperCase()+e.slice(1);e=["is","hook"+e];for(var b in a)if(a.hasOwnProperty(b)){var h=a[b];0===b.indexOf("cmp")&&(b=b.slice(3),b=b.charAt(0).toLowerCase()+b.substring(1),-1===e.indexOf(b)&&(c[b]=h))}return c}function f(a){a.element&&a.element.removeAttribute("data-cmp-is");this._cacheElements(a.element);this._setupProperties(a.options);this._elements.input.addEventListener("invalid",this._onInvalid.bind(this));this._elements.input.addEventListener("input",
this._onInput.bind(this))}function k(){for(var e=document.querySelectorAll(b.self),c=0;c<e.length;c++)new f({element:e[c],options:a(e[c])});e=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;c=document.querySelector("body");(new e(function(c){c.forEach(function(c){c=[].slice.call(c.addedNodes);0<c.length&&c.forEach(function(c){c.querySelectorAll&&[].slice.call(c.querySelectorAll(b.self)).forEach(function(d){new f({element:d,options:a(d)})})})})})).observe(c,{subtree:!0,
childList:!0,characterData:!0})}var b={self:'[data-cmp-is\x3d"formText"]'},h={constraintMessage:{},requiredMessage:{}};f.prototype._onInvalid=function(a){a.target.setCustomValidity("");a.target.validity.typeMismatch?this._properties.constraintMessage&&a.target.setCustomValidity(this._properties.constraintMessage):a.target.validity.valueMissing&&this._properties.requiredMessage&&a.target.setCustomValidity(this._properties.requiredMessage)};f.prototype._onInput=function(a){a.target.setCustomValidity("")};
f.prototype._cacheElements=function(a){this._elements={};this._elements.self=a;a=this._elements.self.querySelectorAll("[data-cmp-hook-form-text]");for(var c=0;c<a.length;c++){var b=a[c],e="formText";e=e.charAt(0).toUpperCase()+e.slice(1);this._elements[b.dataset["cmpHook"+e]]=b}};f.prototype._setupProperties=function(a){this._properties={};for(var c in h)if(h.hasOwnProperty(c)){var b=h[c];this._properties[c]=a&&null!=a[c]?b&&"function"===typeof b.transform?b.transform(a[c]):a[c]:h[c]["default"]}};
"loading"!==document.readyState?k():document.addEventListener("DOMContentLoaded",k)})();
var msftAkamai=function(){var a;return{getAkamaiEdgeScape:function(){return a?Promise.resolve(a):$.get("/aemapi/akamaiApi.akamaiEdgeScape.json").then(function(f){return a=f})}}}(),msftModalManager=function(){function a(){function a(a){$(b).siblings().toArray().filter(function(a){return"SCRIPT"!==a.tagName&&"META"!==a.tagName}).forEach(function(c){a?c.setAttribute("aria-hidden",!0):c.removeAttribute("aria-hidden")})}$(".modal.renderModalOnPageLoad").on("onShow",function(b){a(!0)});$(".modal.renderModalOnPageLoad").on("onHide",
function(b){a(!1)})}function f(){document.querySelectorAll(".renderModalOnPageLoad").forEach(function(a){b.appendChild(a)})}function k(){msGeoSelector.shouldRender().then(function(a){a?(msGeoSelector.render(),msftEmailModal.shouldRender()&&$(document).on(msGeoSelector.CLOSED_EVENT,function(a){msftEmailModal.render()})):msftEmailModal.shouldRender()&&msftEmailModal.render()}).catch(function(){msftEmailModal.shouldRender()&&msftEmailModal.render()})}var b;$(document).ready(function(){b=document.querySelector("#modalsRenderedAfterPageLoad");
a();f();k()})}();
!function(){var a=function(){function a(){return $.when(new Promise(function(a,b){!function l(){if(window.MsOnePlayer)return a();setTimeout(l,200)}()}))}var k="notFetched",b=!1,h=0,e=[];return{fetchScript:function(){return window.MsOnePlayer?$.when():"fetching"===k?a():((c=document.querySelectorAll(".aem-inline-video-component")).forEach(function(a){var f=new MutationObserver(function(a){!function(a,c){b||(a.forEach(function(a){a.addedNodes.forEach(function(a){a.classList&&a.classList.contains("c-video-player")&&(h++,
(a=a.closest(".video-modal"))&&new mwf.Modal({el:a}))})}),h===c&&($('link[href*\x3d"oneplayer.css"]').remove(),b=!0,e.forEach(function(a){a.disconnect()})))}(a,c.length)});f.observe(a,{childList:!0,subtree:!0});e.push(f)}),k="fetching",$.getScript("https://www.microsoft.com/videoplayer/js/oneplayer.js").then(function(){return k="fetched",a()}));var c}}}();window.msftOnePlayerVideo=a}();$(function(){$(".pause-onhide").on("onHide",function(){$(this).find("video").each(function(){this.pause()})})});
$(function(){$(".video-trigger").on("keypress",function(a){a=a.charCode||a.keyCode;32!==a&&13!==a||this.click()})});
window.addEventListener("load",function(){if(window.isFeatureEnabled("perf-tracker-1ds"))if(void 0===window.performance.toJSON)console.log("Performance telemetry was not found");else{var a=window.performance.toJSON();a=JSON.stringify(a);a=JSON.parse(a);var f=a.timing,k=a.navigation;try{let a;var b=window.performance.getEntriesByName("first-contentful-paint")[0].toJSON();window.performance.getEntries();(new PerformanceObserver((b)=>{b=b.getEntries();b=b[b.length-1];a=b.renderTime||b.loadTime})).observe({type:"largest-contentful-paint",
buffered:!0});b.lcp=a}catch(h){}window.telemetry.webAnalyticsPlugin.addTelemetryInitializer(function(a){a.data.timing=f;a.data.navigation=k;a.data.paint=b})}});
!function(){function a(b){if(k[b])return k[b].exports;var h=k[b]={exports:{}};return f[b](h,h.exports,a),h.exports}var f={165:function(){$(function(){var a=$("#emailSup-modal");if(0!==a.length){a=a.find(".countryList");var h=a.attr("data-attribute-lang");if(h){h=h.split("_")[1];var e=a.find("option[selected]");h!==e.attr("value")&&0!==a.find($("option[value\x3d".concat(h,"]"))).length&&(e.removeAttr("selected"),a.find($("option[value\x3d".concat(h,"]"))).attr("selected",""))}}})}},k={};a.n=function(b){var h=
b&&b.__esModule?function(){return b.default}:function(){return b};return a.d(h,{a:h}),h};a.d=function(b,h){for(var e in h)a.o(h,e)&&!a.o(b,e)&&Object.defineProperty(b,e,{enumerable:!0,get:h[e]})};a.o=function(a,h){return Object.prototype.hasOwnProperty.call(a,h)};a(165)}();
var msftEmailModal=function(){function a(){$(".countryList").change(function(){var a=$(".countryList").val(),b=$("#consentNotCanada"),h=$("#consentCanada");"CA"==a?(h.show(),b.hide(),h.attr("aria-hidden","false"),b.attr("aria-hidden","true")):(h.hide(),b.show(),h.attr("aria-hidden","true"),b.attr("aria-hidden","false"))})}var f=new Date;return{shouldRender:function(){if(!document.querySelector("#emailSignupForm"))return!1;var a=localStorage.lastEmailSupPop?new Date(localStorage.lastEmailSupPop):f;
a.setMonth(a.getMonth()+1);return a<=f},render:function(){localStorage.lastEmailSupPop=f;a();var k=document.querySelector("#emailSup-modal");(new mwf.FormValidation({el:document.querySelector("#emailSignupForm"),preventFormSubmission:!0})).el.addEventListener("onValid",function(a){$(".emailSup-swapContent").toggle();$("#emailSup-modal").focus();a=$(k).data("emailsupSelectorEndpoint");var b={email:$(".userEmail").val(),country:$(".countryList").val(),culture:navigator.language};$.post(a,b).fail(function(a,
b,e){localStorage.removeItem("lastEmailSupPop")})});var b={};mwf.version?b.el=k:b.modal=k;(new mwf.Modal(b)).show()}}}();
$(document).ready(function(){var a=$(".modal-header .emailSup-swapContent");if("undefined"!==typeof a&&a){a=a.first().find(":header");var f=document.querySelector(".emailSup-swapContent button.form-group");"undefined"!==typeof f&&f&&(f.dataset.biHn=a.text().trim(),f.dataset.biEhn=a.text().trim(),f.dataset.biCompnm="Modal: Default")}"CA"==$(".countryList").find("option[selected]").attr("value")?($("#consentNotCanada").css("display","none"),$("#consentCanada").css("display","block")):($("#consentCanada").css("display",
"none"),$("#consentNotCanada").css("display","block"))});
var msGeoSelector=function(){function a(){setTimeout(function(){$(document).trigger("ms.geoselector.closed")},3E3)}function f(){var a=["googlebot"],c=!1;if(window.isFeatureEnabled("geo-selector-v2-flighting")&&null!=navigator){var b=navigator.userAgent;b&&b.includes(a[0])&&(c=!0)}return c}function k(d){try{if(!d||f())a();else{"undefined"==typeof q&&(q={language:d.language,region:d.country,localeCode:d.language+"-"+d.country});$(".preferred-redirect-confirm").html(d.marketRedirectConfirm).attr("lang",d.language).attr("hreflang",
d.language).attr("dir",d.dir);$(".preferred-redirect-reject").html(d.marketRedirectReject).attr("lang",d.language).attr("dir",d.dir);$(".preferred-redirect-text").html(d.marketRedirectText).attr("lang",d.language).attr("dir",d.dir);$(".preferred-redirect-heading").html(d.marketRedirectHeading).attr("lang",d.language).attr("dir",d.dir);$(".preferred-redirect-translate").html(d.marketRedirectTranslate).attr("lang",d.language).attr("dir",d.dir);$(".preferred-redirect-cancel").attr("aria-label",d.marketRedirectCancel).attr("lang",
d.language).attr("dir",d.dir);$(".redirect-text").each(function(){var a=b($(this).text(),d.primaryCountry);$(this).html(a)});$(".redirect-heading").each(function(){var a=b($(this).text(),d.secondaryCountry);$(this).html(a)});$(".redirect-confirm").each(function(){var a=b($(this).text(),d.primaryCountry);$(this).html(a);$(this).attr("data-bi-cN",a.trim());$(this).attr("data-bi-ecN",a.trim());$(this).attr("data-bi-hN",$(".preferred-redirect-heading").text().trim());$(this).attr("data-bi-ehN",$(".preferred-redirect-heading").text().trim())});
$(".redirect-reject").each(function(){var a=b($(this).text(),d.secondaryCountry);$(this).html(a);$(this).attr("data-bi-cN",a.trim());$(this).attr("data-bi-ecN",a.trim());$(this).attr("data-bi-hN",$(".preferred-redirect-heading").text().trim());$(this).attr("data-bi-ehN",$(".preferred-redirect-heading").text().trim())});m.language===q.language&&$(".same-language-hide").hide();var c=document.querySelector("#geo-selector-modal");c.addEventListener("onHide",function(d){a()});var k={};mwf.version?k.el=
c:k.modal=c;var l=new mwf.Modal(k);if(null!=d.marketRedirectConfirm&&""!=d.marketRedirectConfirm&&null!=d.marketRedirectReject&&""!=d.marketRedirectReject&&null!=d.marketRedirectText&&""!=d.marketRedirectText&&null!=d.marketRedirectHeading&&""!=d.marketRedirectHeading&&null!=d.marketRedirectTranslate&&""!=d.marketRedirectTranslate)if(window.isFeatureEnabled("geo-selector-v2-flighting")){var g=window.location.href.replace("/"+m.localeCode,"/"+q.localeCode);$.ajax({url:g,type:"HEAD",error:function(){a()},
complete:function(d){switch(d.status){case 200:l.show();break;default:a()}}})}else l.show();else a();$(".redirect-reject").click({currentLocale:m},e);h()}}catch(u){a()}}function b(a,c){return a.replace("{0}",c)}function h(){var a=window.location.href.replace("/"+m.localeCode,"/"+q.localeCode);$(".redirect-confirm").attr("href",a)}function e(a){a="{'r':'1'|'u':'"+a.data.currentLocale.localeCode+"'}";var c=location.hostname;c=c.substring(c.indexOf("."),c.length);$.cookie.raw=!0;$.cookie("mslocale",
a,{expires:45,domain:c,path:"/"})}function c(a){var c=a.split("-");if(1<=c.length)return{language:c[0].toLowerCase(),region:c[1].toLowerCase(),localeCode:a.toLowerCase()}}var m,q,l;return{shouldRender:function(){var a=$("#geo-selector-modal");if(!(a.length&&0<a.length))return Promise.resolve(!1);var b=$.cookie("mslocale");if(void 0!==b)return a=a.data("currentLocaleCode"),b=b.replace(/\|/g,","),b=b.replace(/'/g,'"'),b=$.parseJSON(b),b=c(b.u),(a=c(a))&&b&&a.region===b.region?a=!0:(q=b,m=a,a=!1),Promise.resolve(!a);
a:{if((b=$(".geo-info").data())&&b.country_code&&(l=b.country_code.toLowerCase(),a=a.data("currentLocaleCode"),(m=c(a))&&l)){a=Promise.resolve(m.region!==l);break a}a=Promise.resolve(!0)}return a},render:function(){var c=$("#geo-selector-modal").data("geoSelectorEndpoint"),b=$("#geo-selector-modal").data("geoSelectorCfpath");b="undefined"!==typeof q&&q?{preferredRegion:q.region,preferredLanguage:q.language,currentRegion:m.region,currentLanguage:m.language,cfPath:b,featureFlight:window.isFeatureEnabled("geo-selector-v2-flighting")}:
{currentRegion:m.region,currentLanguage:m.language,preferredAkamaiRegion:l,cfPath:b,featureFlight:window.isFeatureEnabled("geo-selector-v2-flighting")};$.get(c,b).done(function(a){k(a)}).fail(function(){a()})},CLOSED_EVENT:"ms.geoselector.closed"}}();
$(document).ready(function(){document.querySelectorAll("div.content-placement-item .link-group \x3e a").forEach(function(a){var f=a.closest(".content-placement-item");"undefined"!==typeof f&&f&&(a.dataset.biEhn=f.querySelector("h1, h2, h3, h4, h5, h6").textContent,a.dataset.biHn=f.querySelector("h1, h2, h3, h4, h5, h6").textContent,a.dataset.biCompname=f.getAttribute("data-content-placement-style"),f=f.querySelector("img").src,"undefined"!==typeof f&&f&&(a.dataset.biAssetid=f))})});
(function(){var a=$("#uhfSkipToMain"),f=$(".skip-nav"),k="";a.length?k=(k=a.data("href"))&&k.replace("#","")||"mainContent":f.length&&(k=(k=f[0].getAttribute("href"))&&k.replace("#","")||"main");$(".microsoft-template-layout-container").attr("id",k)})();
!function(a){var f=function(a,b,f){var e,c;if(function(){var b,d={lazyClass:"lazyload",loadedClass:"lazyloaded",loadingClass:"lazyloading",preloadClass:"lazypreload",errorClass:"lazyerror",autosizesClass:"lazyautosizes",fastLoadedClass:"ls-is-cached",iframeLoadMode:0,srcAttr:"data-src",srcsetAttr:"data-srcset",sizesAttr:"data-sizes",minSize:40,customMedia:{},init:!0,expFactor:1.5,hFac:.8,loadMode:2,loadHidden:!0,ricTimeout:0,throttleDelay:125};c=a.lazySizesConfig||a.lazysizesConfig||{};for(b in d)b in
c||(c[b]=d[b])}(),!b||!b.getElementsByClassName)return{init:function(){},cfg:c,noSupport:!0};var h=b.documentElement,k=a.HTMLPictureElement,l=a.addEventListener.bind(a),d=a.setTimeout,y=a.requestAnimationFrame||d,D=a.requestIdleCallback,K=/^picture$/i,g=["load","error","lazyincluded","_lazyloaded"],u={},da=Array.prototype.forEach,A=function(a,c){u[c]||(u[c]=new RegExp("(\\s|^)"+c+"(\\s|$)"));return u[c].test(a.getAttribute("class")||"")&&u[c]},z=function(a,c){A(a,c)||a.setAttribute("class",(a.getAttribute("class")||
"").trim()+" "+c)},Q=function(a,c){var b;(b=A(a,c))&&a.setAttribute("class",(a.getAttribute("class")||"").replace(b," "))},R=function(a,c,b){var d=b?"addEventListener":"removeEventListener";b&&R(a,c);g.forEach(function(b){a[d](b,c)})},E=function(a,c,d,f,g){var h=b.createEvent("Event");d||(d={});d.instance=e;h.initEvent(c,!f,!g);h.detail=d;a.dispatchEvent(h);return h},S=function(b,d){var e;!k&&(e=a.picturefill||c.pf)?(d&&d.src&&!b.getAttribute("srcset")&&b.setAttribute("srcset",d.src),e({reevaluate:!0,
elements:[b]})):d&&d.src&&(b.src=d.src)},L=function(a,b,d){for(d=d||a.offsetWidth;d<c.minSize&&b&&!a._lazysizesWidth;)d=b.offsetWidth,b=b.parentNode;return d},H=function(){var a,c,e=[],f=[],g=e,h=function(){var b=g;g=e.length?f:e;a=!0;for(c=!1;b.length;)b.shift()();a=!1},k=function(e,f){a&&!f?e.apply(this,arguments):(g.push(e),c||(c=!0,(b.hidden?d:y)(h)))};k._lsFlush=h;return k}(),M=function(a,c){return c?function(){H(a)}:function(){var c=this,b=arguments;H(function(){a.apply(c,b)})}},ea=function(a){var b,
e=0,g=c.throttleDelay,h=c.ricTimeout,k=function(){b=!1;e=f.now();a()},l=D&&49<h?function(){D(k,{timeout:h});h!==c.ricTimeout&&(h=c.ricTimeout)}:M(function(){d(k)},!0);return function(a){if(a=!0===a)h=33;if(!b){b=!0;var c=g-(f.now()-e);0>c&&(c=0);a||9>c?l():d(l,c)}}},W=function(a){var c,b,e=function(){c=null;a()},h=function(){var a=f.now()-b;99>a?d(h,99-a):(D||e)(e)};return function(){b=f.now();c||(c=d(h,99))}},P=function(){var g,k,m,q,n,U,V,F,G,I,u,x,D=/^img$/i,L=/^iframe$/i,P="onscroll"in a&&!/(gle|ing)bot/.test(navigator.userAgent),
N=0,v=0,C=-1,X=function(a){v--;if(!a||0>v||!a.target)v=0},Y=function(a){null==x&&(x="hidden"==(getComputedStyle(b.body,null)||{}).visibility);return x||!("hidden"==(getComputedStyle(a.parentNode,null)||{}).visibility&&"hidden"==(getComputedStyle(a,null)||{}).visibility)},Z=function(){var a,d,f,l,n=e.elements;if((q=c.loadMode)&&8>v&&(a=n.length)){var t=0;for(C++;t<a;t++)if(n[t]&&!n[t]._lazyRace)if(!P||e.prematureUnveil&&e.prematureUnveil(n[t]))J(n[t]);else{(l=n[t].getAttribute("data-expand"))&&(f=
1*l)||(f=N);if(!m){var m=!c.expand||1>c.expand?500<h.clientHeight&&500<h.clientWidth?500:370:c.expand;e._defEx=m;var p=m*c.expFactor;var r=c.hFac;x=null;N<p&&1>v&&2<C&&2<q&&!b.hidden?(N=p,C=0):N=1<q&&1<C&&6>v?m:0}if(A!==f){U=innerWidth+f*r;V=innerHeight+f;var y=-1*f;var A=f}p=n[t].getBoundingClientRect();if((p=(u=p.bottom)>=y&&(F=p.top)<=V&&(I=p.right)>=y*r&&(G=p.left)<=U&&(u||I||G||F)&&(c.loadHidden||Y(n[t])))&&!(p=k&&3>v&&!l&&(3>q||4>C))){var B=n[t];var w=f;p=B;B=Y(B);F-=w;u+=w;G-=w;for(I+=w;B&&
(p=p.offsetParent)&&p!=b.body&&p!=h;)(B=0<((getComputedStyle(p,null)||{}).opacity||1))&&"visible"!=(getComputedStyle(p,null)||{}).overflow&&(w=p.getBoundingClientRect(),B=I>w.left&&G<w.right&&u>w.top-1&&F<w.bottom+1);p=B}if(p){J(n[t]);var z=!0;if(9<v)break}else!z&&k&&!d&&4>v&&4>C&&2<q&&(g[0]||c.preloadAfterLoad)&&(g[0]||!l&&(u||I||G||F||"auto"!=n[t].getAttribute(c.sizesAttr)))&&(d=g[0]||n[t])}d&&!z&&J(d)}},r=ea(Z),ba=function(a){var b=a.target;b._lazyCache?delete b._lazyCache:(X(a),z(b,c.loadedClass),
Q(b,c.loadingClass),R(b,aa),E(b,"lazyloaded"))},fa=M(ba),aa=function(a){fa({target:a.target})},ha=function(a,b){var d=a.getAttribute("data-load-mode")||c.iframeLoadMode;0==d?a.contentWindow.location.replace(b):1==d&&(a.src=b)},ia=function(a){var b,d=a.getAttribute(c.srcsetAttr);(b=c.customMedia[a.getAttribute("data-media")||a.getAttribute("media")])&&a.setAttribute("media",b);d&&a.setAttribute("srcset",d)},ja=M(function(a,b,e,f,g){var h,k;if(!(k=E(a,"lazybeforeunveil",b)).defaultPrevented){f&&(e?
z(a,c.autosizesClass):a.setAttribute("sizes",f));f=a.getAttribute(c.srcsetAttr);e=a.getAttribute(c.srcAttr);if(g)var n=(h=a.parentNode)&&K.test(h.nodeName||"");var l=b.firesLoad||"src"in a&&(f||e||n);k={target:a};z(a,c.loadingClass);l&&(clearTimeout(m),m=d(X,2500),R(a,aa,!0));n&&da.call(h.getElementsByTagName("source"),ia);f?a.setAttribute("srcset",f):e&&!n&&(L.test(a.nodeName)?ha(a,e):a.src=e);g&&(f||n)&&S(a,{src:e})}a._lazyRace&&delete a._lazyRace;Q(a,c.lazyClass);H(function(){var b=a.complete&&
1<a.naturalWidth;if(!l||b)b&&z(a,c.fastLoadedClass),ba(k),a._lazyCache=!0,d(function(){"_lazyCache"in a&&delete a._lazyCache},9);"lazy"==a.loading&&v--},!0)}),J=function(a){if(!a._lazyRace){var b=D.test(a.nodeName),d=b&&(a.getAttribute(c.sizesAttr)||a.getAttribute("sizes")),e="auto"==d;if(!e&&k||!b||!a.getAttribute("src")&&!a.srcset||a.complete||A(a,c.errorClass)||!A(a,c.lazyClass)){var f=E(a,"lazyunveilread").detail;e&&T.updateElem(a,!0,a.offsetWidth);a._lazyRace=!0;v++;ja(a,f,e,d,b)}}},ka=W(function(){c.loadMode=
3;r()}),ca=function(){3==c.loadMode&&(c.loadMode=2);ka()},O=function(){k||(999>f.now()-n?d(O,999):(k=!0,c.loadMode=3,r(),l("scroll",ca,!0)))};return{_:function(){n=f.now();e.elements=b.getElementsByClassName(c.lazyClass);g=b.getElementsByClassName(c.lazyClass+" "+c.preloadClass);l("scroll",r,!0);l("resize",r,!0);l("pageshow",function(a){if(a.persisted){var d=b.querySelectorAll("."+c.loadingClass);d.length&&d.forEach&&y(function(){d.forEach(function(a){a.complete&&J(a)})})}});a.MutationObserver?(new MutationObserver(r)).observe(h,
{childList:!0,subtree:!0,attributes:!0}):(h.addEventListener("DOMNodeInserted",r,!0),h.addEventListener("DOMAttrModified",r,!0),setInterval(r,999));l("hashchange",r,!0);"focus mouseover click load transitionend animationend".split(" ").forEach(function(a){b.addEventListener(a,r,!0)});/d$|^c/.test(b.readyState)?O():(l("load",O),b.addEventListener("DOMContentLoaded",r),d(O,2E4));e.elements.length?(Z(),H._lsFlush()):r()},checkElems:r,unveil:J,_aLSL:ca}}(),T=function(){var a,d=M(function(a,b,c,d){var e;
a._lazysizesWidth=d;d+="px";a.setAttribute("sizes",d);if(K.test(b.nodeName||"")){b=b.getElementsByTagName("source");var f=0;for(e=b.length;f<e;f++)b[f].setAttribute("sizes",d)}c.detail.dataAttr||S(a,c.detail)}),e=function(a,b,c){var e=a.parentNode;e&&(c=L(a,e,c),b=E(a,"lazybeforesizes",{width:c,dataAttr:!!b}),b.defaultPrevented||(c=b.detail.width)&&c!==a._lazysizesWidth&&d(a,e,b,c))},f=W(function(){var b,c=a.length;if(c)for(b=0;b<c;b++)e(a[b])});return{_:function(){a=b.getElementsByClassName(c.autosizesClass);
l("resize",f)},checkElems:f,updateElem:e}}(),x=function(){!x.i&&b.getElementsByClassName&&(x.i=!0,T._(),P._())};return d(function(){c.init&&x()}),e={cfg:c,autoSizer:T,loader:P,init:x,uP:S,aC:z,rC:Q,hC:A,fire:E,gW:L,rAF:H}}(a,a.document,Date);a.lazySizes=f;"object"==typeof module&&module.exports&&(module.exports=f)}("undefined"!=typeof window?window:{});window.lazySizesConfig=window.lazySizesConfig||{};lazySizesConfig.loadMode=1;lazySizesConfig.preloadAfterLoad=!0;