(function(g){var window=this;'use strict';var C8a=function(a){g.X.call(this,{F:"div",N:"ytp-miniplayer-ui"});this.vf=!1;this.player=a;this.S(a,"minimized",this.ih);this.S(a,"onStateChange",this.EL)},D8a=function(a){g.OO.call(this,a);
this.u=new g.mE(this);this.j=new C8a(this.player);this.j.hide();g.iO(this.player,this.j.element,4);a.Ff()&&(this.load(),g.po(a.getRootNode(),"ytp-player-minimized",!0));this.player.K("web_rounded_containers")&&g.po(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(C8a,g.X);g.k=C8a.prototype;
g.k.UI=function(){this.tooltip=new g.PS(this.player,this);g.N(this,this.tooltip);g.iO(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Hc=new g.IP(this.player);g.N(this,this.Hc);this.Ai=new g.X({F:"div",N:"ytp-miniplayer-scrim"});g.N(this,this.Ai);this.Ai.Ca(this.element);this.S(this.Ai.element,"click",this.jE);var a=new g.X({F:"button",Ga:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.EL()]});g.N(this,a);a.Ca(this.Ai.element);this.S(a.element,"click",this.En);
a=new g.L2(this.player,this);g.N(this,a);a.Ca(this.Ai.element);this.Gs=new g.X({F:"div",N:"ytp-miniplayer-controls"});g.N(this,this.Gs);this.Gs.Ca(this.Ai.element);this.S(this.Gs.element,"click",this.jE);var b=new g.X({F:"div",N:"ytp-miniplayer-button-container"});g.N(this,b);b.Ca(this.Gs.element);a=new g.X({F:"div",N:"ytp-miniplayer-play-button-container"});g.N(this,a);a.Ca(this.Gs.element);var c=new g.X({F:"div",N:"ytp-miniplayer-button-container"});g.N(this,c);c.Ca(this.Gs.element);this.CS=new g.jR(this.player,
this,!1);g.N(this,this.CS);this.CS.Ca(b.element);b=new g.hR(this.player,this);g.N(this,b);b.Ca(a.element);this.nextButton=new g.jR(this.player,this,!0);g.N(this,this.nextButton);this.nextButton.Ca(c.element);this.Di=new g.BS(this.player,this);g.N(this,this.Di);this.Di.Ca(this.Ai.element);this.yc=new g.uR(this.player,this);g.N(this,this.yc);g.iO(this.player,this.yc.element,4);this.ZD=new g.X({F:"div",N:"ytp-miniplayer-buttons"});g.N(this,this.ZD);g.iO(this.player,this.ZD.element,4);a=new g.X({F:"button",
Ga:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.EL()]});g.N(this,a);a.Ca(this.ZD.element);this.S(a.element,"click",this.En);a=new g.X({F:"button",Ga:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},W:[g.LL()]});g.N(this,a);a.Ca(this.ZD.element);this.S(a.element,"click",this.H1);this.S(this.player,"presentingplayerstatechange",this.Vc);this.S(this.player,"appresize",this.Ab);this.S(this.player,"fullscreentoggled",this.Ab);this.Ab()};
g.k.show=function(){this.Ge=new g.$n(this.Ft,null,this);this.Ge.start();this.vf||(this.UI(),this.vf=!0);0!==this.player.getPlayerState()&&g.X.prototype.show.call(this);this.yc.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.Ge&&(this.Ge.dispose(),this.Ge=void 0);g.X.prototype.hide.call(this);this.player.Ff()||(this.vf&&this.yc.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.Ge&&(this.Ge.dispose(),this.Ge=void 0);g.X.prototype.ra.call(this)};
g.k.En=function(){this.player.stopVideo();this.player.Pa("onCloseMiniplayer")};
g.k.H1=function(){this.player.playVideo()};
g.k.jE=function(a){if(a.target===this.Ai.element||a.target===this.Gs.element)this.player.V().K("kevlar_miniplayer_play_pause_on_scrim")?g.AK(this.player.Db())?this.player.pauseVideo():this.player.playVideo():this.player.Pa("onExpandMiniplayer")};
g.k.ih=function(){g.po(this.player.getRootNode(),"ytp-player-minimized",this.player.Ff())};
g.k.ke=function(){this.yc.ac();this.Di.ac()};
g.k.Ft=function(){this.ke();this.Ge&&this.Ge.start()};
g.k.Vc=function(a){g.V(a.state,32)&&this.tooltip.hide()};
g.k.Ab=function(){g.NR(this.yc,0,this.player.fb().getPlayerSize().width,!1);g.xR(this.yc)};
g.k.EL=function(a){this.player.Ff()&&(0===a?this.hide():this.show())};
g.k.vc=function(){return this.tooltip};
g.k.Df=function(){return!1};
g.k.pg=function(){return!1};
g.k.yj=function(){return!1};
g.k.Dk=function(){return!1};
g.k.Ef=function(){return!1};
g.k.YA=function(){};
g.k.Ao=function(){};
g.k.cw=function(){};
g.k.Fl=function(){return null};
g.k.aD=function(){return null};
g.k.Fz=function(){return null};
g.k.vj=function(){return new g.zl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Pt=function(a,b,c,d,e){var f=0,h=d=0,l=g.Nl(a);if(b){c=g.jo(b,"ytp-prev-button")||g.jo(b,"ytp-next-button");var m=g.jo(b,"ytp-play-button"),n=g.jo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Ll(b,this.element),h=b.x,f=b.y-12):n&&(h=g.jo(b,"ytp-miniplayer-button-top-left"),f=g.Ll(b,this.element),b=g.Nl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.fb().getPlayerSize().width;e=f+(e||0);l=g.xg(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.On=function(){};
g.k.yk=function(){return!1};
g.k.ZA=function(){};
g.k.tx=function(){};
g.k.tp=function(){};
g.k.hC=function(){};
g.k.gq=function(){};g.v(D8a,g.OO);g.k=D8a.prototype;g.k.onVideoDataChange=function(){if(this.player.K("web_rounded_containers")&&this.player.getVideoData()){var a=16/9;a=this.player.getVideoAspectRatio()>a+.1;g.po(this.player.getRootNode(),"ytp-rounded-miniplayer-extra-wide-video",a)}};
g.k.create=function(){g.OO.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Pj=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.NO("miniplayer",D8a);})(_yt_player);
